### ISSUE TITLE
Refactor String -> Enum conversions to use TryFrom

### ISSUE THREAD

**Issue by asonix** [asonix/release-manager#4]
Two places in the code (specifically for the `OS` and `Arch` enums, we have extended match structures that convert a given `&str` into an enum discriminant. We can clean up the logic here by replacing these with something along the lines of:
```Rust
if let Ok(value) = arch_str.try_into() {
    // call_things_on(value)
}

// somewhere else in the code
impl TryFrom<&str> for Arch {
    fn try_from(...) { ... }
}
```

**Comment by ghost** [comment]
Hello, 
I have migrated the match structures into the TryFrom implementation, 
Would you accept the following in place of your reccomended if statement? 

```
      for (os, value) in self.config.iter() {
            let opsys = OS::try_from(os.as_ref());
            build_os(&mut targets, opsys.expect(&format!("{}, is not a valid Operating System!",os)), value);
        }
```

**Comment by asonix** [comment]
Try not to use 'expect' since we don't really want to have our program panic in these cases. Printing a message and ignoring the invalid target is probably better

**Comment by ghost** [comment]
Copy that, I'll make the modifications :>

Thanks,
Aidan

**Comment by ghost** [comment]
Okay, Instead of 'expect' it now checks the result with 'is_err' before reaching inside it with 'unwrap.'

**Comment by asonix** [comment]
Nice, thanks!
